In [1]:
import numpy as np

In [1]:
ll = 0
for l1 in range(1,4):
    for l2 in range(l1, 4):
        ll += 1
        print(ll, l1, l2)

1 1 1
2 1 2
3 1 3
4 2 2
5 2 3
6 3 3


In [ ]:
r = np.random.randn(1000000)

In [24]:
# Explore how the turbulent Mach number from Tian et al. 2023 behaves
stds = np.array([0.05, 0.1, 0.2])
a = np.array([1 + i * r for i in stds])

In [25]:
a.mean(axis=1), a.std(axis=1)

(array([0.99998236, 0.99996473, 0.99992945]),
 array([0.04998816, 0.09997632, 0.19995264]))

In [26]:
a_rms = np.sqrt(np.mean(a**2, axis=1))
a_rms, (a_rms-1)/(stds**2)

(array([1.00123101, 1.00495011, 1.01972544]),
 array([0.4924055 , 0.49501076, 0.49313596]))